# Generated by Django 5.0.2 on 2024-02-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_descricao_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='facebook',
            field=models.URLField(default='#', max_length=100, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='instagram',
            field=models.URLField(default='#', max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='twitter',
            field=models.URLField(default='#', max_length=100, verbose_name='Twitter'),
        ),
    ]
